name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@96dde98a034ab75fec7884f9161bc12759275d36
        with:
          token: ${{ secrets.METRICS_TOKEN }}          
          base: header, repositories
          config_display: large
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer, scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage          
          plugin_traffic: yes
